project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "qmd/*.qmd"
    - "!notebooks/001_graphs.ipynb"
bibliography: refs.bib
csl: ieee-access.csl
execute:
  echo: false
jupyter: python3
website:
  title: "Panorama actual de las energías renovables y la geotermia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: qmd/01_panorama_mundial.qmd
        text: 1 Panorama mundial
      - href: qmd/02_impacto_ambiental.qmd
        text: 2 Impacto ambiental
      - href: qmd/03_comparativo_renovables.qmd
        text: 3 Comparativo renovables
      - href: qmd/04_geotermia_mundial.qmd
        text: 4 Geotermia mundial
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



