---
title: "1 La geotermia como energía renovable"
bibliography: refs.bib
csl: ieee-access.csl
execute:
  echo: false
jupyter: python3
format:
  html:
    theme: "default"
    code-overflow: scroll
---

# 1.1 Panorama mundial de energía y energías renovables

## Suministro total de energía por fuente, mundo, 1990-2023, @iea_world_2025

```{python}
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

f = "data/3960AFa8.csv"
df = pd.read_csv(f,skiprows=3)
energy_columns = [col for col in df.columns if col not in ['Año', 'Unidades']]

fig = px.area(df, 
              x='Año', 
              y=energy_columns,
              labels={'value': 'Energía primaria [TJ]', 'variable': 'Fuente'})
fig.update_layout(hovermode='x unified')
fig.show()
```

```{python}
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

f = "data/3960AFa8.csv"
df = pd.read_csv(f,skiprows=3)
energy_columns = [col for col in df.columns if col not in ['Año', 'Unidades']]
fig = px.area(df, 
              x='Año', 
              y=energy_columns,
              groupnorm="percent",
              labels={'value': '%', 'variable': 'Fuente'})
fig.update_layout(hovermode='x unified')
fig.show()
```

## Consumo de energía primaria por región, 2024 @energy_institute_-_statistical_review_of_world_energy_2025__with_major_processing_by_our_world_in_data_primary_2025

```{python}
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
f = "data/primary-energy-consumption-by-region.csv"
df2 = pd.read_csv(f)
region_mapping = {
    'Africa (EI)': 'África',
    'Asia Pacific (EI)': 'Asia Pacífico',
    'Europe (EI)': 'Europa',
    'Middle East (EI)': 'Medio Oriente',
    'North America (EI)': 'Norteamérica',
    'South and Central America (EI)': 'Sudamérica y Centroamérica'
}
df2['Entity'] = df2['Entity'].replace(region_mapping)
fig = px.area(
    df2,
    x="Year",
    y="Primary energy consumption",
    color="Entity",
    labels={
        "Year": "Año",
        "Primary energy consumption": "Energía primaria [TJ]",
        "Entity": "Región",
    },
)
fig.update_layout(hovermode="x unified")
fig.show()
```

```{python}
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
f = "data/primary-energy-consumption-by-region.csv"
df2 = pd.read_csv(f)
region_mapping = {
    'Africa (EI)': 'África',
    'Asia Pacific (EI)': 'Asia Pacífico',
    'Europe (EI)': 'Europa',
    'Middle East (EI)': 'Medio Oriente',
    'North America (EI)': 'Norteamérica',
    'South and Central America (EI)': 'Sudamérica y Centroamérica'
}
df2['Entity'] = df2['Entity'].replace(region_mapping)
fig = px.area(
    df2,
    x="Year",
    y="Primary energy consumption",
    color="Entity",
    labels={
        "Year": "Año",
        "Primary energy consumption": "%",
        "Entity": "Región",
    },
    groupnorm="percent"
)
fig.update_layout(hovermode="x unified")
fig.show()
```

## Contribución de las energías renovables al suministro total de energía primaria, 2023

## Consumo de petróleo per cápita por región, 2023

## Contribución de la generación eléctrica por fuente, 2023

## Contribución de la generación eléctrica por región, 2023

## Total del consumo mundial por fuente de energía, 2023 - 2050

## Mayores importadores netos de combustibles fósiles, 2023

# 1.2 Impacto ambiental del consumo de energía

## Emisiones de CO2 por fuente de energía, 2023

## Contribución estimada de gases de efecto invernadero (GEI) al calentamiento antropogénico global, 2023

## Datos clave

* Aumento de emisiones por generación eléctrica 2000-2023: %
* Cambio de las emisiones de CO2: %
* Crecimiento proyectado de ER: % / a
* Crecimiento proyectado de nuclear: % / a
* Contribución proyectada de fósiles: % / a
* Aumento de consumo de gas: % / a

# 1.3 Escenario comparativo con otras fuentes renovables de energía

## Emisiones CO2

Comparación de emisiones de CO2 de geotermia y fuentes convencionales

## Emisiones NOx

# 1.5 Escenario mundial actual de explotación de los recursos geotérmicos

## Mapa de capacidad instalada geotérmica {.scrollable}
Los datos de @international_renewable_energy_agency_renewable_2025 corresponden al promedio de 2024, los de @global_energy_monitor_global_2025 a marzo de 2025 y los de @geoenergy_global_2026 a finales de 2025.
```{python}

import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px

df = pd.read_csv("data/merged_geothermal.csv")

df_melted = df[["Country", "2024 [1]", "2025 [2]", "2025 [3]"]].copy()
df_melted.columns = ["País", "2024 [1]", "2025 [2]", "2025 [3]"]

df_long = df_melted.melt(id_vars=["País"],
                       var_name="Año",
                       value_name="Capacidad [MW]")

fig = px.choropleth(df_long,
                    locations="País",
                    locationmode="country names",
                    color="Capacidad [MW]",
                    hover_name="País",
                    animation_frame="Año",
                    color_continuous_scale=px.colors.sequential.Plasma);

fig.layout.updatemenus[0].buttons[0].args[1]['frame']['duration'] = 1500
fig.layout.updatemenus[0].buttons[0].args[1]['transition']['duration'] = 500

fig.show();
```

## Top 10 países con mayor capacidad instalada geotérmica {.scrollable}

```{python}
#| class-output: hscroll
top_10_2024 = df[["Country", "2024 [1]"]].sort_values(by="2024 [1]", ascending=False).head(10)
top_10_2025_2 = df[["Country", "2025 [2]"]].sort_values(by="2025 [2]", ascending=False).head(10)
top_10_2025_2 = top_10_2025_2.reset_index(drop=True)
top_10_2025_3 = df[["Country", "2025 [3]"]].sort_values(by="2025 [3]", ascending=False).head(10)
top_10_2025_3 = top_10_2025_3.reset_index(drop=True)
top_10 = pd.concat([top_10_2024, top_10_2025_2, top_10_2025_3], axis=1)
top_10.columns = ["País", "2024 [1]", "País", "2025 [2]", "País", "2025 [3]"]
top_10
```
## Referencias

::: {#refs}
:::